import type { BentoDoc } from "@/components/ppt-editor";

const FONT_STACK =
  "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif";
const INK = "#f8fafc";
const MUTED = "#94a3b8";
const ACCENT = "#818cf8";
const SLIDE_BG = "#0f172a";

/** ~1.5s sine tone, built in code so the sample needs no binary asset. */
const TINY_WAV = makeToneWavDataUri();

/**
 * Build a small PCM WAV (16-bit mono sine tone) as a data URI, so the sample
 * deck can embed an audible clip without shipping a binary.
 */
function makeToneWavDataUri(seconds = 1.5, frequency = 440, sampleRate = 8000): string {
  const sampleCount = Math.round(seconds * sampleRate);
  const dataSize = sampleCount * 2;
  const buffer = new ArrayBuffer(44 + dataSize);
  const view = new DataView(buffer);
  const writeAscii = (offset: number, text: string) => {
    for (let i = 0; i < text.length; i += 1) {
      view.setUint8(offset + i, text.charCodeAt(i));
    }
  };

  writeAscii(0, "RIFF");
  view.setUint32(4, 36 + dataSize, true);
  writeAscii(8, "WAVE");
  writeAscii(12, "fmt ");
  view.setUint32(16, 16, true);
  view.setUint16(20, 1, true); // PCM
  view.setUint16(22, 1, true); // mono
  view.setUint32(24, sampleRate, true);
  view.setUint32(28, sampleRate * 2, true);
  view.setUint16(32, 2, true); // block align
  view.setUint16(34, 16, true); // bits per sample
  writeAscii(36, "data");
  view.setUint32(40, dataSize, true);
  for (let i = 0; i < sampleCount; i += 1) {
    const value = Math.round(Math.sin((i * frequency * 2 * Math.PI) / sampleRate) * 12000);
    view.setInt16(44 + i * 2, value, true);
  }

  const bytes = new Uint8Array(buffer);
  let binary = "";
  for (const byte of bytes) {
    binary += String.fromCharCode(byte);
  }
  return `data:audio/wav;base64,${btoa(binary)}`;
}

/**
 * A small, styled two-slide deck used to seed the showcase editor via
 * `initialDoc`, so the demo opens on real content instead of a blank shell.
 */
export const SAMPLE_DOC: BentoDoc = {
  format: "bento/slides",
  version: 1,
  docId: "00000000-0000-4000-8000-000000000001",
  title: "PptEditor demo",
  meta: {
    author: "Demo Author",
    company: "Example Inc",
    subject: "ppt-editor export demo",
    keywords: "demo, export, pptx",
  },
  size: { width: 1280, height: 720 },
  theme: {
    background: SLIDE_BG,
    color: INK,
    accent: "#6366f1",
    fontFamily: FONT_STACK,
    chartPalette: ["#6366f1", "#94a3b8", "#f59e0b", "#10b981"],
  },
  slides: [
    {
      id: "slide-title",
      background: SLIDE_BG,
      transition: "fade",
      notes: "",
      elements: [
        {
          id: "title-accent-bar",
          type: "shape",
          shape: "rect",
          x: 120,
          y: 224,
          w: 64,
          h: 8,
          rotation: 0,
          opacity: 1,
          fill: "#6366f1",
          stroke: "transparent",
          strokeWidth: 0,
          radius: 4,
          shadow: { x: 0, y: 6, blur: 16, color: "#000000" },
        },
        {
          id: "title-kicker",
          type: "text",
          x: 120,
          y: 248,
          w: 700,
          h: 36,
          rotation: 0,
          opacity: 1,
          html: "PPT EDITOR",
          fontSize: 18,
          fontFamily: FONT_STACK,
          fontWeight: 600,
          color: ACCENT,
          align: "left",
          valign: "top",
          lineHeight: 1.2,
          letterSpacing: 3,
          role: "kicker",
        },
        {
          id: "title-heading",
          type: "text",
          x: 120,
          y: 292,
          w: 1040,
          h: 220,
          rotation: 0,
          opacity: 1,
          html: "Presentations,<br>built in <b>code</b>",
          fontSize: 88,
          fontFamily: FONT_STACK,
          fontWeight: 800,
          color: INK,
          align: "left",
          valign: "top",
          lineHeight: 1.05,
          role: "title",
          shadow: { x: 3, y: 3, blur: 10, color: "rgba(0,0,0,0.55)" },
        },
        {
          id: "title-subtitle",
          type: "text",
          x: 120,
          y: 524,
          w: 940,
          h: 80,
          rotation: 0,
          opacity: 1,
          html: "A React component that embeds the bento slides editor, same-origin.",
          fontSize: 26,
          fontFamily: FONT_STACK,
          fontWeight: 400,
          color: MUTED,
          align: "left",
          valign: "top",
          lineHeight: 1.4,
          role: "subtitle",
        },
      ],
    },
    {
      id: "slide-highlights",
      background: SLIDE_BG,
      transition: "fade",
      notes: "",
      elements: [
        {
          id: "highlights-heading",
          type: "text",
          x: 120,
          y: 120,
          w: 1040,
          h: 90,
          rotation: 0,
          opacity: 1,
          html: "Highlights",
          fontSize: 56,
          fontFamily: FONT_STACK,
          fontWeight: 800,
          color: INK,
          align: "left",
          valign: "top",
          lineHeight: 1.1,
          role: "title",
        },
        ...highlightRow("row-1", 264, "Same-origin iframe", "direct access to the bento runtime"),
        ...highlightRow("row-2", 380, "Typed controller", "loadDoc, serialize, undo, redo"),
        ...highlightRow("row-3", 496, "Bundled shell", "nothing to host — mounted via srcdoc"),
      ],
    },
    {
      id: "slide-data",
      background: SLIDE_BG,
      transition: "fade",
      notes: "",
      elements: [
        {
          id: "data-heading",
          type: "text",
          x: 120,
          y: 60,
          w: 1040,
          h: 70,
          rotation: 0,
          opacity: 1,
          html: "Table & media",
          fontSize: 44,
          fontFamily: FONT_STACK,
          fontWeight: 800,
          color: INK,
          align: "left",
          valign: "top",
          lineHeight: 1.1,
          role: "title",
        },
        {
          id: "data-table",
          type: "table",
          x: 120,
          y: 170,
          w: 1040,
          h: 300,
          rotation: 0,
          opacity: 1,
          columns: [{ w: 2 }, { w: 1 }, { w: 1 }],
          header: true,
          rows: [
            { cells: [{ html: "Metric" }, { html: "2024" }, { html: "2025" }] },
            { cells: [{ html: "Revenue" }, { html: "12.4" }, { html: "19.1" }] },
            { cells: [{ html: "Cost" }, { html: "8.2" }, { html: "11.3" }] },
            { cells: [{ html: "Margin" }, { html: "34%" }, { html: "41%" }] },
          ],
          style: {
            headerBg: "#6366f1",
            headerColor: "#f8fafc",
            zebra: "#1e293b",
            borderColor: "#334155",
            borderWidth: 1,
            cellPadX: 12,
            cellPadY: 8,
            fontSize: 18,
            color: "#e2e8f0",
            radius: 8,
          },
        },
        {
          id: "data-audio",
          type: "media",
          kind: "audio",
          x: 120,
          y: 520,
          w: 300,
          h: 80,
          rotation: 0,
          opacity: 1,
          src: TINY_WAV,
          controls: true,
        },
      ],
    },
    {
      id: "slide-charts",
      background: SLIDE_BG,
      transition: "fade",
      notes: "",
      elements: [
        {
          id: "charts-heading",
          type: "text",
          x: 120,
          y: 60,
          w: 1040,
          h: 70,
          rotation: 0,
          opacity: 1,
          html: "Charts",
          fontSize: 44,
          fontFamily: FONT_STACK,
          fontWeight: 800,
          color: INK,
          align: "left",
          valign: "top",
          lineHeight: 1.1,
          role: "title",
        },
        label("charts-lbl-bar", 120, 150, "BAR"),
        {
          id: "charts-bar",
          type: "chart",
          preset: "bar",
          x: 120,
          y: 180,
          w: 520,
          h: 220,
          rotation: 0,
          opacity: 1,
          option: {
            xAxis: { data: ["Q1", "Q2", "Q3", "Q4"] },
            series: [
              { name: "Revenue", type: "bar", data: [12, 19, 9, 15] },
              { name: "Cost", type: "bar", data: [8, 11, 7, 10] },
            ],
          },
        },
        label("charts-lbl-line", 660, 150, "LINE"),
        {
          id: "charts-line",
          type: "chart",
          preset: "line",
          x: 660,
          y: 180,
          w: 520,
          h: 220,
          rotation: 0,
          opacity: 1,
          option: {
            xAxis: { data: ["Q1", "Q2", "Q3", "Q4"] },
            series: [{ name: "Trend", type: "line", data: [4, 9, 6, 14] }],
          },
        },
        label("charts-lbl-pie", 120, 430, "PIE"),
        {
          id: "charts-pie",
          type: "chart",
          preset: "pie",
          x: 120,
          y: 460,
          w: 520,
          h: 220,
          rotation: 0,
          opacity: 1,
          option: {
            series: [
              {
                name: "Share",
                type: "pie",
                data: [
                  { name: "Product A", value: 40 },
                  { name: "Product B", value: 32 },
                  { name: "Product C", value: 28 },
                ],
              },
            ],
          },
        },
        label("charts-lbl-scatter", 660, 430, "SCATTER"),
        {
          id: "charts-scatter",
          type: "chart",
          preset: "scatter",
          x: 660,
          y: 460,
          w: 520,
          h: 220,
          rotation: 0,
          opacity: 1,
          option: {
            series: [
              {
                name: "Samples",
                type: "scatter",
                data: [
                  [1, 3],
                  [2, 5],
                  [3, 4],
                  [4, 8],
                  [5, 6],
                ],
              },
            ],
          },
        },
      ],
    },
    {
      id: "slide-rich-text",
      background: SLIDE_BG,
      transition: "fade",
      notes: "",
      elements: [
        {
          id: "rich-heading",
          type: "text",
          x: 120,
          y: 60,
          w: 1040,
          h: 70,
          rotation: 0,
          opacity: 1,
          html: "Rich text",
          fontSize: 44,
          fontFamily: FONT_STACK,
          fontWeight: 800,
          color: INK,
          align: "left",
          valign: "top",
          lineHeight: 1.1,
          role: "title",
        },
        label("rich-lbl-inline", 120, 150, "INLINE"),
        {
          id: "rich-inline",
          type: "text",
          x: 120,
          y: 184,
          w: 500,
          h: 70,
          rotation: 0,
          opacity: 1,
          html: "Plain, <b>bold</b>, <i>italic</i>, <u>underline</u>, <b><i>bold italic</i></b>, <b><u>bold underline</u></b>.",
          fontSize: 22,
          fontFamily: FONT_STACK,
          fontWeight: 400,
          color: INK,
          align: "left",
          valign: "top",
          lineHeight: 1.4,
          role: "body",
        },
        label("rich-lbl-colors", 120, 270, "ELEMENT COLORS"),
        colorWord("rich-cw-rose", 120, 304, "#f43f5e", "rose"),
        colorWord("rich-cw-amber", 220, 304, "#f59e0b", "amber"),
        colorWord("rich-cw-emerald", 330, 304, "#10b981", "emerald"),
        colorWord("rich-cw-sky", 460, 304, "#0ea5e9", "sky"),
        label("rich-lbl-breaks", 120, 380, "LINE BREAKS"),
        {
          id: "rich-breaks",
          type: "text",
          x: 120,
          y: 414,
          w: 500,
          h: 110,
          rotation: 0,
          opacity: 1,
          html: "First line.<br>Second line after a break.<br><br>Fourth line (blank line above).",
          fontSize: 20,
          fontFamily: FONT_STACK,
          fontWeight: 400,
          color: INK,
          align: "left",
          valign: "top",
          lineHeight: 1.35,
          role: "body",
        },
        label("rich-lbl-entities", 120, 540, "ENTITIES"),
        {
          id: "rich-entities",
          type: "text",
          x: 120,
          y: 574,
          w: 500,
          h: 50,
          rotation: 0,
          opacity: 1,
          html: "Entities: &amp; &lt;tag&gt; &quot;quotes&quot; — literal.",
          fontSize: 20,
          fontFamily: FONT_STACK,
          fontWeight: 400,
          color: INK,
          align: "left",
          valign: "top",
          lineHeight: 1.35,
          role: "body",
        },
        label("rich-lbl-weights", 660, 150, "FONT WEIGHT"),
        {
          id: "rich-weight-regular",
          type: "text",
          x: 660,
          y: 184,
          w: 500,
          h: 40,
          rotation: 0,
          opacity: 1,
          html: "Weight 400 (regular)",
          fontSize: 22,
          fontFamily: FONT_STACK,
          fontWeight: 400,
          color: INK,
          align: "left",
          valign: "top",
          lineHeight: 1.4,
          role: "body",
        },
        {
          id: "rich-weight-bold",
          type: "text",
          x: 660,
          y: 228,
          w: 500,
          h: 40,
          rotation: 0,
          opacity: 1,
          html: "Weight 800 (element bold)",
          fontSize: 22,
          fontFamily: FONT_STACK,
          fontWeight: 800,
          color: INK,
          align: "left",
          valign: "top",
          lineHeight: 1.4,
          role: "body",
        },
        label("rich-lbl-align", 660, 250, "ALIGNMENT"),
        {
          id: "rich-center",
          type: "text",
          x: 660,
          y: 284,
          w: 500,
          h: 40,
          rotation: 0,
          opacity: 1,
          html: "Centered line",
          fontSize: 20,
          fontFamily: FONT_STACK,
          fontWeight: 400,
          color: INK,
          align: "center",
          valign: "top",
          lineHeight: 1.3,
          role: "body",
        },
        {
          id: "rich-right",
          type: "text",
          x: 660,
          y: 334,
          w: 500,
          h: 40,
          rotation: 0,
          opacity: 1,
          html: "Right-aligned line",
          fontSize: 20,
          fontFamily: FONT_STACK,
          fontWeight: 400,
          color: INK,
          align: "right",
          valign: "top",
          lineHeight: 1.3,
          role: "body",
        },
        label("rich-lbl-nested", 660, 400, "NESTED TAGS"),
        {
          id: "rich-mixed",
          type: "text",
          x: 660,
          y: 434,
          w: 500,
          h: 90,
          rotation: 0,
          opacity: 1,
          html: "One block, <b>two <i>styles</i></b> combined <b><i><u>all three</u></i></b>, <s>strikethrough</s>.",
          fontSize: 32,
          fontFamily: FONT_STACK,
          fontWeight: 400,
          color: INK,
          align: "left",
          valign: "top",
          lineHeight: 1.3,
          role: "body",
        },
        label("rich-lbl-spacing", 660, 540, "SPACING"),
        {
          id: "rich-spacing",
          type: "text",
          x: 660,
          y: 574,
          w: 500,
          h: 40,
          rotation: 0,
          opacity: 1,
          html: "LETTER SPACING",
          fontSize: 20,
          fontFamily: FONT_STACK,
          fontWeight: 600,
          color: ACCENT,
          align: "left",
          valign: "top",
          lineHeight: 1.2,
          letterSpacing: 3,
          role: "body",
        },
      ],
    },
    {
      id: "slide-shadows",
      background: SLIDE_BG,
      transition: "fade",
      notes: "",
      elements: [
        {
          id: "shadow-heading",
          type: "text",
          x: 120,
          y: 60,
          w: 1040,
          h: 70,
          rotation: 0,
          opacity: 1,
          html: "Shadows",
          fontSize: 44,
          fontFamily: FONT_STACK,
          fontWeight: 800,
          color: INK,
          align: "left",
          valign: "top",
          lineHeight: 1.1,
          role: "title",
        },
        label("shadow-lbl-glow", 120, 150, "GLOW ON DARK"),
        {
          id: "shadow-neon",
          type: "text",
          x: 120,
          y: 184,
          w: 500,
          h: 76,
          rotation: 0,
          opacity: 1,
          html: "Neon glow",
          fontSize: 48,
          fontFamily: FONT_STACK,
          fontWeight: 800,
          color: "#f8fafc",
          align: "left",
          valign: "top",
          lineHeight: 1.1,
          role: "body",
          shadow: { x: 0, y: 0, blur: 24, color: "#f43f5e" },
        },
        {
          id: "shadow-card-glow",
          type: "shape",
          shape: "rect",
          x: 120,
          y: 290,
          w: 460,
          h: 150,
          rotation: 0,
          opacity: 1,
          fill: "#1e293b",
          stroke: "transparent",
          strokeWidth: 0,
          radius: 12,
          shadow: { x: 0, y: 0, blur: 36, color: "#6366f1" },
        },
        {
          id: "shadow-ellipse-glow",
          type: "shape",
          shape: "ellipse",
          x: 140,
          y: 480,
          w: 200,
          h: 130,
          rotation: 0,
          opacity: 1,
          fill: "#f59e0b",
          stroke: "transparent",
          strokeWidth: 0,
          radius: 0,
          shadow: { x: 0, y: 0, blur: 28, color: "#f59e0b" },
        },
        {
          id: "shadow-panel",
          type: "shape",
          shape: "rect",
          x: 660,
          y: 150,
          w: 500,
          h: 460,
          rotation: 0,
          opacity: 1,
          fill: "#f8fafc",
          stroke: "transparent",
          strokeWidth: 0,
          radius: 16,
        },
        {
          id: "shadow-lbl-drop",
          type: "text",
          x: 700,
          y: 180,
          w: 400,
          h: 26,
          rotation: 0,
          opacity: 1,
          html: "DROP ON LIGHT",
          fontSize: 14,
          fontFamily: FONT_STACK,
          fontWeight: 600,
          color: "#64748b",
          align: "left",
          valign: "top",
          lineHeight: 1.2,
          letterSpacing: 2,
        },
        {
          id: "shadow-text-drop",
          type: "text",
          x: 700,
          y: 224,
          w: 420,
          h: 64,
          rotation: 0,
          opacity: 1,
          html: "Hard shadow",
          fontSize: 40,
          fontFamily: FONT_STACK,
          fontWeight: 800,
          color: "#0f172a",
          align: "left",
          valign: "top",
          lineHeight: 1.1,
          role: "body",
          shadow: { x: 5, y: 5, blur: 6, color: "#000000" },
        },
        {
          id: "shadow-card-drop",
          type: "shape",
          shape: "rect",
          x: 700,
          y: 320,
          w: 420,
          h: 120,
          rotation: 0,
          opacity: 1,
          fill: "#1e293b",
          stroke: "transparent",
          strokeWidth: 0,
          radius: 12,
          shadow: { x: 0, y: 10, blur: 24, color: "#000000" },
        },
        {
          id: "shadow-dot-drop",
          type: "shape",
          shape: "ellipse",
          x: 700,
          y: 470,
          w: 90,
          h: 90,
          rotation: 0,
          opacity: 1,
          fill: "#f59e0b",
          stroke: "transparent",
          strokeWidth: 0,
          radius: 0,
          shadow: { x: 6, y: 6, blur: 10, color: "#000000" },
        },
      ],
    },
  ],
  modified: "2024-01-01T00:00:00.000Z",
};

/**
 * A single word in an element-level color.
 */
function colorWord(
  id: string,
  x: number,
  y: number,
  color: string,
  text: string,
): BentoDoc["slides"][number]["elements"][number] {
  return {
    id,
    type: "text",
    x,
    y,
    w: 100,
    h: 40,
    rotation: 0,
    opacity: 1,
    html: text,
    fontSize: 22,
    fontFamily: FONT_STACK,
    fontWeight: 600,
    color,
    align: "left",
    valign: "top",
    lineHeight: 1.3,
    role: "body",
  };
}

/**
 * A small caps section label.
 */
function label(
  id: string,
  x: number,
  y: number,
  text: string,
): BentoDoc["slides"][number]["elements"][number] {
  return {
    id,
    type: "text",
    x,
    y,
    w: 500,
    h: 26,
    rotation: 0,
    opacity: 1,
    html: text,
    fontSize: 14,
    fontFamily: FONT_STACK,
    fontWeight: 600,
    color: MUTED,
    align: "left",
    valign: "top",
    lineHeight: 1.2,
    letterSpacing: 2,
  };
}

/**
 * A bullet row: an accent dot plus a lead-in phrase and supporting copy.
 */
function highlightRow(
  prefix: string,
  y: number,
  lead: string,
  rest: string,
): BentoDoc["slides"][number]["elements"] {
  return [
    {
      id: `${prefix}-dot`,
      type: "shape",
      shape: "ellipse",
      x: 120,
      y: y + 12,
      w: 16,
      h: 16,
      rotation: 0,
      opacity: 1,
      fill: "#6366f1",
      stroke: "transparent",
      strokeWidth: 0,
      radius: 0,
    },
    {
      id: `${prefix}-text`,
      type: "text",
      x: 164,
      y,
      w: 960,
      h: 64,
      rotation: 0,
      opacity: 1,
      html: `<b>${lead}</b> — ${rest}`,
      fontSize: 30,
      fontFamily: FONT_STACK,
      fontWeight: 400,
      color: INK,
      align: "left",
      valign: "top",
      lineHeight: 1.3,
      role: "body",
    },
  ];
}
